export {default as DeletionIcon} from './deletion.vue'
export {default as EditIcon} from './edit.vue'
export {default as FurnitureIcon} from './furniture.vue'
export {default as LayerIcon} from './layer.vue'
export {default as MeasureIcon} from './measure.vue'
export {default as MoveIcon} from './move.vue'
export {default as MultipleSelectIcon} from './multipleSelect.vue'
export {default as PaintIcon} from './paint.vue'
export {default as RoofIcon} from './roof.vue'
export {default as SelectIcon} from './select.vue'
export {default as SettingsIcon} from './settings.vue'
export {default as ZoomInIcon} from './zoomIn.vue'
export {default as ZoomOutIcon} from './zoomOut.vue'
export {default as Plan2D} from './plan2d.vue'
// @ts-ignore
export {default as Plan3D} from './plan3d.vue'
export {default as PlanVR} from './planvr.vue'
export {default as MoreIcon} from './more.vue'